import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#F1F8E9',
  },
  progress: {
    fontSize: 16,
    color: '#2E7D32',
    fontWeight: '600',
    marginBottom: 8,
  },
  storyBox: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginHorizontal: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    alignItems: 'center',
  },
  emoji: { fontSize: 40, marginBottom: 8 },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2E7D32',
    marginBottom: 12,
  },
  storyText: {
    fontSize: 17,
    color: '#333',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 20,
  },
  storyActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  listenBtn: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#4CAF50',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  listenText: { color: '#2E7D32', fontSize: 15, fontWeight: '700' },
  continueBtn: {
    backgroundColor: '#4CAF50',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  continueText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  questionBox: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginHorizontal: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    alignItems: 'center',
  },
  questionText: {
    fontSize: 19,
    fontWeight: '700',
    color: '#2E7D32',
    textAlign: 'center',
    marginBottom: 16,
  },
  optionsColumn: { gap: 12, width: '100%' },
  optionBtn: {
    backgroundColor: '#4CAF50',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  correctBtn: { backgroundColor: '#2E7D32' },
  optionText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#4CAF50' },
  badgeWrong: { backgroundColor: '#F44336' },
});
