import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#E3F2FD',
  },
  progress: {
    fontSize: 16,
    color: '#1976D2',
    fontWeight: '600',
    marginBottom: 8,
  },
  prompt: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0D47A1',
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 16,
    marginTop: 20,
  },
  optionBtn: {
    width: 90,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#2196F3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  correctBtn: { backgroundColor: '#4CAF50' },
  optionText: { fontSize: 22, fontWeight: '900', color: '#fff' },
  confirmBtn: {
    marginTop: 20,
    backgroundColor: '#4CAF50',
    borderRadius: 20,
    paddingHorizontal: 32,
    paddingVertical: 14,
  },
  confirmText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  compareRow: {
    flexDirection: 'row',
    gap: 24,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  compareOption: { alignItems: 'center', gap: 8 },
  compareLabel: { fontSize: 24, fontWeight: '900', color: '#0D47A1' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#1565C0' },
  badgeWrong: { backgroundColor: '#F44336' },
});
