import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    marginTop: 8,
  },
  countArea: {
    minHeight: 70,
    marginHorizontal: 16,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#81C784',
    borderStyle: 'dashed',
    backgroundColor: '#F1F8E9',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
    padding: 8,
    gap: 6,
  },
  countAreaHint: {
    fontSize: 13,
    color: '#558B2F',
    fontWeight: '600',
    alignSelf: 'center',
    marginHorizontal: 'auto',
  },
  bundleBadge: {
    alignSelf: 'center',
    marginTop: 6,
    fontSize: 15,
    fontWeight: '800',
    color: '#fff',
    backgroundColor: '#2E7D32',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  tray: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#EFEBE9',
    borderRadius: 14,
    marginHorizontal: 16,
  },
  palitoWrap: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  palitoTouchArea: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  palito: {
    width: 8,
    height: 32,
    borderRadius: 4,
    backgroundColor: '#A1887F',
  },
  palitoDropped: {
    backgroundColor: '#33691E',
  },
});
