import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', paddingTop: 12, backgroundColor: '#E3F2FD' },
  progress: { fontSize: 16, color: '#1976D2', fontWeight: '600', marginBottom: 4 },
  instruction: { fontSize: 20, fontWeight: '700', color: '#0D47A1', marginBottom: 16, textAlign: 'center' },
  comparisonRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 24, paddingHorizontal: 16 },
  side: {
    flex: 1,
    alignItems: 'center',
    minHeight: 100,
    backgroundColor: '#BBDEFB',
    borderRadius: 16,
    padding: 10,
    justifyContent: 'center',
  },
  numberText: { fontSize: 52, fontWeight: '900', color: '#0D47A1' },
  expressionText: { fontSize: 26, fontWeight: '900', color: '#0D47A1', textAlign: 'center' },
  symbolSlot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionMark: { fontSize: 24, fontWeight: '900', color: '#90CAF9' },
  symbolRow: { flexDirection: 'row', gap: 20 },
  symbolBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2196F3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  correctSymBtn: { backgroundColor: '#4CAF50' },
  wrongSymBtn:   { backgroundColor: '#F44336' },
  symbolBtnText: { fontSize: 36, fontWeight: '900', color: '#fff', lineHeight: 42 },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#1565C0' },
  badgeWrong: { backgroundColor: '#F44336' },
});
