import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#E3F2FD',
  },
  progress: {
    fontSize: 16,
    color: '#1976D2',
    fontWeight: '600',
    marginBottom: 8,
  },
  questionBox: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginHorizontal: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    marginBottom: 20,
    alignItems: 'center',
  },
  emoji: { fontSize: 40, marginBottom: 8 },
  questionText: {
    fontSize: 19,
    fontWeight: '700',
    color: '#0D47A1',
    textAlign: 'center',
    lineHeight: 26,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 16,
  },
  optionBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2196F3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  correctBtn: { backgroundColor: '#4CAF50' },
  dimBtn: { opacity: 0.4 },
  optionText: { fontSize: 28, fontWeight: '900', color: '#fff' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#1565C0' },
  badgeWrong: { backgroundColor: '#F44336' },
});
