import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#1A0E33',
  },
  progress: {
    fontSize: 16,
    color: '#CE93D8',
    fontWeight: '600',
    marginBottom: 8,
  },
  programRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  programHint: { color: '#CE93D8', fontSize: 14, fontStyle: 'italic' },
  programChip: {
    backgroundColor: '#4A148C',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  programChipText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  paletteRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  blockBtn: {
    backgroundColor: '#7E57C2',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  blockBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
  },
  undoBtn: {
    backgroundColor: '#4A148C',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  undoText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  runBtn: {
    backgroundColor: '#4CAF50',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  runBtnDisabled: { opacity: 0.4 },
  runText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#4CAF50' },
  badgeWrong: { backgroundColor: '#F44336' },
});
