import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#F1F8E9',
  },
  progress: {
    fontSize: 16,
    color: '#2E7D32',
    fontWeight: '600',
    marginBottom: 8,
  },
  prompt: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2E7D32',
    textAlign: 'center',
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  wordBox: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 32,
    paddingVertical: 18,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    marginBottom: 20,
  },
  wordText: {
    fontSize: 32,
    fontWeight: '900',
    color: '#2E7D32',
    letterSpacing: 1,
  },
  sentenceBox: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sentenceWord: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
  },
  sentenceWordTarget: {
    color: '#2E7D32',
    textDecorationLine: 'underline',
    fontWeight: '900',
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 16,
  },
  optionBtn: {
    minWidth: 110,
    height: 56,
    borderRadius: 16,
    paddingHorizontal: 14,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  correctBtn: { backgroundColor: '#2E7D32' },
  optionText: { fontSize: 16, fontWeight: '800', color: '#fff' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#4CAF50' },
  badgeWrong: { backgroundColor: '#F44336' },
});
