import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 12,
    backgroundColor: '#E3F2FD',
  },
  progress: {
    fontSize: 16,
    color: '#1976D2',
    fontWeight: '600',
    marginBottom: 4,
  },
  question: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0D47A1',
    marginBottom: 12,
  },
  scroll: { flex: 1, width: '100%' },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  bounceWrap: { alignItems: 'center' },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  optionBtn: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#2196F3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  correctBtn: { backgroundColor: '#4CAF50' },
  optionText: { fontSize: 26, fontWeight: '900', color: '#fff' },
  badge: {
    marginBottom: 16,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  badgeCorrect: { backgroundColor: '#1565C0' },
  badgeWrong: { backgroundColor: '#F44336' },
});
