import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 16,
    backgroundColor: '#FFF3E0',
  },
  progress: {
    fontSize: 16,
    color: '#E65100',
    fontWeight: '600',
    marginBottom: 8,
  },
  prompt: {
    fontSize: 17,
    fontWeight: '700',
    color: '#E65100',
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  placedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    minHeight: 56,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  placedHint: { color: '#BF6000', fontSize: 14, fontStyle: 'italic' },
  placedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  availableRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  availableChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FF9800',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chipEmoji: { fontSize: 20 },
  chipLabel: { fontSize: 14, fontWeight: '700', color: '#fff' },
  confirmBtn: {
    backgroundColor: '#4CAF50',
    borderRadius: 20,
    paddingHorizontal: 32,
    paddingVertical: 14,
  },
  confirmBtnDisabled: { opacity: 0.4 },
  confirmText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  badge: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 24,
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  badgeCorrect: { backgroundColor: '#4CAF50' },
  badgeWrong: { backgroundColor: '#F44336' },
});
